spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/security
        username: postgres
        password: robertas
    jpa:
        hibernate:
            ddl-auto: update
